"""build_index.py — agent entry points: kb/CLAUDE.md + kb/SCOPE.md.

CLAUDE.md: navigation contract (read order, grep strategy, conventions).
SCOPE.md:  coverage manifest — fully parsed vs shallow vs external-by-design,
           plus the filters used at capture. Absence from the KB is deliberate,
           and this file makes that explicit to the agent (see plan §5, v1.3).
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pp_common as pp
import parse_canvas as pc


def read_json(path: str) -> dict:
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def count_md(pattern: str) -> int:
    return len([p for p in glob.glob(pattern)])


def build_scope(cfg: dict, out_dir: str, crossrefs: dict, meta_index: dict, flow_index: dict) -> str:
    filters = {}
    filters.update(cfg.get("filters") or {})
    filters.update(meta_index.get("filters") or {})
    filters.update(flow_index.get("filters") or {})

    L = ["# Coverage Manifest", "",
         "> This file declares **what this KB does and does not cover**.",
         "> If something is absent here, it is intentionally out of scope — do not assume generation failure.", ""]

    tables = crossrefs.get("tables", [])
    flows = sorted(crossrefs.get("flows", {}))
    apps = sorted(crossrefs.get("apps", {}))

    L += ["## In scope (fully parsed)", ""]
    L.append(f"- **Tables ({len(tables)})**: " + (", ".join(f"`{t}`" for t in tables) or "—"))
    L.append(f"- **Flows ({len(flows)})**: " + (", ".join(flows) or "—"))
    screen_lines = []
    shallow_lines = []
    for app in apps:
        try:
            merged, provenance = pc.load_app(os.path.join(cfg["canvasSourcePath"], app, "Src"))
        except Exception:
            continue
        patterns = (cfg.get("filters", {}) or {}).get("screens") or []
        full, shallow = pc.compute_screen_tiers(merged.get("Screens") or {}, provenance, patterns)
        for s in sorted(full):
            screen_lines.append(f"{app}/{s}")
        for s, reason in sorted(shallow.items()):
            shallow_lines.append(f"{app}/{s} — {reason}")
    L.append(f"- **Canvas screens — full parse ({len(screen_lines)})**: " + (", ".join(screen_lines) or "—"))

    L += ["", "## Shallow index only (structure known, details not parsed)", ""]
    if shallow_lines:
        L.append(f"- **Canvas screens ({len(shallow_lines)})**:")
        L += [f"  - {s}" for s in shallow_lines]
    else:
        L.append("- none")

    L += ["", "## External / boundary references (referenced but intentionally not in KB)", ""]
    ext = crossrefs.get("externalTables", [])
    L.append("- **Tables**: " + (", ".join(f"`{t}`" for t in ext) if ext else "none detected"))
    L.append("  (marked `(external — not in KB)` in REFERENCES.md and diagrams)")

    L += ["", "## Filters applied at capture", "",
          "```json", json.dumps(filters, ensure_ascii=False, indent=2) or "{}", "```", ""]
    return "\n".join(L)


def build_claude_md(cfg: dict, out_dir: str, crossrefs: dict, meta_index: dict, flow_index: dict) -> str:
    env = meta_index.get("environment") or flow_index.get("environment") or cfg.get("dataverseUrl", "?")
    captured = meta_index.get("capturedAt") or flow_index.get("capturedAt") or "?"
    tables = len(crossrefs.get("tables", []))
    flows = len(crossrefs.get("flows", {}))
    apps = len(crossrefs.get("apps", {}))
    screens = count_md(os.path.join(out_dir, "apps", "*", "screens", "*.md"))
    comps = count_md(os.path.join(out_dir, "apps", "*", "components", "*.md"))

    return f"""# Power Platform Knowledge Base

> Snapshot: environment `{env}` | captured {captured}
> Generated by pp-kb-builder. Rebuild is deterministic from `_raw/`.

## How to read this KB

1. **Start here, then [SCOPE.md](SCOPE.md)** — the coverage manifest: what is fully
   parsed vs shallow-indexed vs intentionally out of scope. Absence is deliberate.
2. Then [REFERENCES.md](REFERENCES.md) — the cross-artifact matrix: which table is
   used by which app/flow. External objects are marked `(external — not in KB)`.
3. Drill into the artifact you need:
   - `dataverse/tables/<logicalname>.md` — columns, choices, relationships, used-by
   - `flows/<flowname>.md` — trigger, action DAG (mermaid), connectors, tables touched
   - `apps/<AppName>/overview.md` — app props, data sources, screen navigation graph
   - `apps/<AppName>/screens|components/<name>.md` — control tree, formulas, data refs
4. If a summary lacks detail: `_raw/` holds the sanitized capture (metadata, flow
   clientdata). Canvas sources live outside this KB (read-only).
5. Prefer `grep`-style search over reading whole directories; files are self-contained.

## Contents

| Area | Location | Count |
|---|---|---|
| Tables | `dataverse/tables/` | {tables} |
| Flows | `flows/` | {flows} |
| Canvas apps | `apps/` | {apps} ({screens} screens + {comps} components documented) |

## Conventions

- Tables/columns are referenced by **logical name**; display names appear on first use.
- Mermaid diagrams render in VS Code / Typora / Git platforms.
- Secrets never appear here: sensitive material is stripped at capture
  (see `_raw/REDACTION-LOG.md` when present).
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate kb/CLAUDE.md and kb/SCOPE.md")
    ap.add_argument("--config", help="path to pp-kb.config.json")
    args = ap.parse_args()

    cfg = pp.load_config(args.config)
    out_dir = cfg["outputDir"]
    crossrefs = read_json(os.path.join(out_dir, "_raw", "crossrefs.json"))
    if not crossrefs:
        pp.die("no crossrefs.json — run build_crossrefs.py first")
    meta_index = read_json(os.path.join(out_dir, "_raw", "metadata", "_index.json"))
    flow_index = read_json(os.path.join(out_dir, "_raw", "flows", "_index.json"))

    pp.write_text(os.path.join(out_dir, "CLAUDE.md"),
                  build_claude_md(cfg, out_dir, crossrefs, meta_index, flow_index))
    pp.write_text(os.path.join(out_dir, "SCOPE.md"),
                  build_scope(cfg, out_dir, crossrefs, meta_index, flow_index))
    pp.log("[index] CLAUDE.md + SCOPE.md written")

    hits = pp.redaction_scan_dir(out_dir)
    if hits:
        pp.die("redaction scan FAILED:\n" + "\n".join(hits))
    pp.log("[index] redaction scan: PASS")


if __name__ == "__main__":
    main()
